CREATE TABLE students (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  teacher_id INTEGER
    REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  student_first TEXT NOT NULL,
  student_last TEXT NOT NULL,
  birth_date TEXT NOT NULL,
  parent_email TEXT
);